# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "fr-FR"
title: "Mon Health Coach"
name: "Mon Health Coach"
description: "Un accompagnement individualisé pour votre santé, qui vous écoute, vous soutient, vous guide vers des changements durables..."
baseurl: "/"
url: "https://monhealthcoach.com"

# Build settings
theme: minimal-mistakes-jekyll

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - README.md

logo: "/assets/images/Logo_MHC.jpg"

# Site Author
author:
  name             : "Jérôme Triomphe"
  avatar           : "/assets/images/Jérôme Kitesurf Boracay.jpg"
  bio              : "Integrative Nutrition Health Coach"
  location         : "France"
  links:
    - label: "Email"
      icon: "fa-solid fa-envelope"
      url: "mailto:monhealthcoach@gmail.com"
    - label: "Téléphone"
      icon: "fa-solid fa-mobile-screen"
      url: "tel:+33699468553"
    - label: "Instagram"
      icon: "fa-brands fa-instagram"
      url: "https://www.instagram.com/monhealthcoach/"
    - label: "Twitter"
      icon: "fa-brands fa-x-twitter"
      url: "https://twitter.com/MonHealthCoach"
    - label: "BlueSky"
      icon: "fa-brands fa-bluesky"
      url: "https://bsky.app/profile/monhealthcoach.bsky.social"
    - label: "Facebook"
      icon: "fa-brands fa-facebook"
      url: "https://www.facebook.com/monhealthcoach/"

atom_feed:
  hide: true

analytics:
  provider: "google"
  google:
    tracking_id: "G-366RDECVQM"
